### ISSUE TITLE
Translaate broke if have double quotation marks

### ISSUE THREAD

**Issue by jtaboracastejon** [Uncover-F/TAS#6]
First of all thanks for your work!

I'm testing the API Request with this text:

Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.

I've noticed that if the text has double quotation marks it brokes and stop translate, should I sanitize those chars?

**Comment by Uncover-F** [comment]
Unfortunately, the problem you are facing is on our end. The Character Limit is 623, however we recommend 600 Characters as a buffer. As our translation system uses AI, the translation may not be accurate if the input does not make sense.

For example, it can translate 623 Characters if it is reasonable, like "Hello, Lorem Ipsum is a real phrase". Your request is reasonable, so it can translate 623 Chars. If it is gibberish like "9201380" then an Unknown Error may occur.

As, to the  quotation marks, to take safe measures use common but rarely used character or use something like %9924.

We are extremely sorry for any inconvenience caused, however due to this API being free, we must use cheaper AI models. 

Kind Regards,
Uncover Team
